Description: >
  This template create S3 manager template file
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-template
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-template

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub
              - "${ResourcesBucketArn}/*"
              - ResourcesBucketArn: !GetAtt S3Bucket.Arn
            Principal: "*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId

Outputs:
  S3TemplateBucket:
    Description: S3 bucket template cfn
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3TemplateBucket"
